nodeLinker: node-modules

# packageExtensions:
#   "@types/htmlparser2@*":
#     dependencies:
#       domutils: "*"
#   "@types/react-html-parser@*":
#     dependencies:
#       htmlparser2: "*"
#   "@types/react@*":
#     dependencies:
#       prop-types: "*"
#       scheduler: "*"
#   styled-jsx@*:
#     dependencies:
#       process: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs
